const food = [
	{
		name: "McDonald's",
		gif: "",
		imagePop: "https://i.imgur.com/URRi5OK.png",
		backgroundImage: "https://i.imgur.com/wmOnMtn.jpg",
		logo: "https://i.imgur.com/XLipBe7.png",
		learnMoreLink: "",
	},
	{
		name: "KFC",
		gif: "",
		imagePop: "https://i.imgur.com/ZbZA96c.png",
		backgroundImage: "https://i.imgur.com/jcWfoTT.jpg",
		logo: "https://i.imgur.com/KXyOHiO.png",
		learnMoreLink: "",
	},
	{
		name: "Hungry Jack's",
		gif: "",
		imagePop: "https://i.imgur.com/bTyYaTm.png",
		backgroundImage: "https://i.imgur.com/3rSFjOQ.png",
		logo: "https://i.imgur.com/dAMi78W.png",
		learnMoreLink: "",
	},
	{
		name: "Subway",
		gif: "",
		imagePop: "https://i.imgur.com/BsuVTq3.png",
		backgroundImage: "https://i.imgur.com/wHPWPJs.jpg",
		logo: "https://i.imgur.com/lu7O32q.png",
		learnMoreLink: "",
	},
	{
		name: "Barnacle Bill",
		gif: "",
		imagePop: "https://i.imgur.com/MKmx3zy.png",
		backgroundImage: "https://i.imgur.com/9TAjpOa.jpg",
		logo: "https://i.imgur.com/q1xTT5e.png",
		learnMoreLink: "",
	},
	{
		name: "Red Rooster",
		gif: "",
		imagePop: "https://i.imgur.com/YxZBcoM.png",
		backgroundImage: "https://i.imgur.com/1j9c6EF.png",
		logo: "https://i.imgur.com/QUpJN16.png",
		learnMoreLink: "",
	},
	{
		name: "Taco Bell",
		gif: "",
		imagePop: "https://i.imgur.com/WiYUfox.png",
		backgroundImage: "https://i.imgur.com/0aeRt0B.png",
		logo: "https://i.imgur.com/nEJ1GDV.png",
		learnMoreLink: "",
	},
	{
		name: "Guzman Y Gomez",
		gif: "",
		imagePop: "https://i.imgur.com/DXlQzRu.png",
		backgroundImage: "https://i.imgur.com/NGID0UU.jpg",
		logo: "https://i.imgur.com/6lXZ7wq.png",
		learnMoreLink: "",
	},
	{
		name: "Oporto",
		gif: "",
		imagePop: "https://i.imgur.com/gKheFpT.png",
		backgroundImage: "https://i.imgur.com/lchylND.jpg",
		logo: "https://i.imgur.com/H2iE75I.png",
		learnMoreLink: "",
	},
	{
		name: "Mad Mex",
		gif: "",
		imagePop: "https://i.imgur.com/W2wuR7N.png",
		backgroundImage: "https://i.imgur.com/RyYVfUL.jpg",
		logo: "https://i.imgur.com/pRBBI7u.png",
		learnMoreLink: "",
	},
	{
		name: "Domino's",
		gif: "",
		imagePop: "https://i.imgur.com/xkmDiNO.png",
		backgroundImage: "https://i.imgur.com/FriJXqq.gif",
		logo: "https://i.imgur.com/G4xDAFS.png",
		learnMoreLink: "",
	},
	{
		name: "Grill'd",
		gif: "",
		imagePop: "https://i.imgur.com/5xEONFv.png",
		backgroundImage: "https://i.imgur.com/pfQGf7i.jpg",
		logo: "https://i.imgur.com/8V7ygXm.png",
		learnMoreLink: "",
	},
	{
		name: "Pizza Hut",
		gif: "",
		imagePop: "https://i.imgur.com/M6ywT4n.png",
		backgroundImage: "https://i.imgur.com/1H8aHc2.jpg",
		logo: "https://i.imgur.com/NbpIMkN.png",
		learnMoreLink: "",
	},
	{
		name: "Zambrero",
		gif: "",
		imagePop: "https://i.imgur.com/kDJ0kef.png",
		backgroundImage: "https://i.imgur.com/bwICmhF.jpg",
		logo: "https://i.imgur.com/t9EF4JY.png",
		learnMoreLink: "",
	},
	{
		name: "Salsas",
		gif: "",
		imagePop: "https://i.imgur.com/B8rT0hp.png",
		backgroundImage: "https://i.imgur.com/XyUs8C3.png",
		logo: "https://i.imgur.com/X2rWMlK.png",
		learnMoreLink: "",
	},
];

export default food;
