const food = [
    {
        label: "Barnacle Bill",
        value: "barnaclebill",
        gif: "",
        imagePop: "https://i.imgur.com/MKmx3zy.png",
        backgroundImage: "https://i.imgur.com/9TAjpOa.jpg",
        logo: "https://i.imgur.com/q1xTT5e.png",
        learnMoreLink: "",
    },
    {
        label: "Domino's",
        value: "dominos",
        gif: "",
        imagePop: "https://i.imgur.com/xkmDiNO.png",
        backgroundImage: "https://i.imgur.com/FriJXqq.gif",
        logo: "https://i.imgur.com/G4xDAFS.png",
        learnMoreLink: "",
    },
    {
        label: "Grill'd",
        value: "grilld",
        gif: "",
        imagePop: "https://i.imgur.com/5xEONFv.png",
        backgroundImage: "https://i.imgur.com/pfQGf7i.jpg",
        logo: "https://i.imgur.com/8V7ygXm.png",
        learnMoreLink: "",
    },
    {
        label: "Guzman Y Gomez",
        value: "gyg",
        gif: "",
        imagePop: "https://i.imgur.com/DXlQzRu.png",
        backgroundImage: "https://i.imgur.com/NGID0UU.jpg",
        logo: "https://i.imgur.com/6lXZ7wq.png",
        learnMoreLink: "",
    },
    {
        label: "Hungry Jack's",
        value: "hungryjacks",
        gif: "",
        imagePop: "https://i.imgur.com/bTyYaTm.png",
        backgroundImage: "https://i.imgur.com/3rSFjOQ.png",
        logo: "https://i.imgur.com/dAMi78W.png",
        learnMoreLink: "",
    },
    {
        label: "KFC",
        value: "kfc",
        gif: "",
        imagePop: "https://i.imgur.com/ZbZA96c.png",
        backgroundImage: "https://i.imgur.com/jcWfoTT.jpg",
        logo: "https://i.imgur.com/KXyOHiO.png",
        learnMoreLink: "",
    },
    {
        label: "Mad Mex",
        value: "madmex",
        gif: "",
        imagePop: "https://i.imgur.com/W2wuR7N.png",
        backgroundImage: "https://i.imgur.com/RyYVfUL.jpg",
        logo: "https://i.imgur.com/pRBBI7u.png",
        learnMoreLink: "",
    },
    {
        label: "McDonald's",
        value: "mcdonalds",
        gif: "",
        imagePop: "https://i.imgur.com/URRi5OK.png",
        backgroundImage: "https://i.imgur.com/wmOnMtn.jpg",
        logo: "https://i.imgur.com/XLipBe7.png",
        learnMoreLink: "",
    },
    {
        label: "Oporto",
        value: "oporto",
        gif: "",
        imagePop: "https://i.imgur.com/gKheFpT.png",
        backgroundImage: "https://i.imgur.com/lchylND.jpg",
        logo: "https://i.imgur.com/H2iE75I.png",
        learnMoreLink: "",
    },
    {
        label: "Red Rooster",
        value: "redrooster",
        gif: "",
        imagePop: "https://i.imgur.com/YxZBcoM.png",
        backgroundImage: "https://i.imgur.com/1j9c6EF.png",
        logo: "https://i.imgur.com/QUpJN16.png",
        learnMoreLink: "",
    },
    {
        label: "Salsas",
        value: "salsas",
        gif: "",
        imagePop: "https://i.imgur.com/B8rT0hp.png",
        backgroundImage: "https://i.imgur.com/XyUs8C3.png",
        logo: "https://i.imgur.com/X2rWMlK.png",
        learnMoreLink: "",
    },
    {
        label: "Subway",
        value: "subway",
        gif: "",
        imagePop: "https://i.imgur.com/BsuVTq3.png",
        backgroundImage: "https://i.imgur.com/wHPWPJs.jpg",
        logo: "https://i.imgur.com/lu7O32q.png",
        learnMoreLink: "",
    },
    {
        label: "Taco Bell",
        value: "tacobell",
        gif: "",
        imagePop: "https://i.imgur.com/WiYUfox.png",
        backgroundImage: "https://i.imgur.com/0aeRt0B.png",
        logo: "https://i.imgur.com/nEJ1GDV.png",
        learnMoreLink: "",
    },
    {
        label: "Pizza Hut",
        value: "pizzahut",
        gif: "",
        imagePop: "https://i.imgur.com/M6ywT4n.png",
        backgroundImage: "https://i.imgur.com/1H8aHc2.jpg",
        logo: "https://i.imgur.com/NbpIMkN.png",
        learnMoreLink: "",
    },
    {
        label: "Zambrero",
        value: "zambrero",
        gif: "",
        imagePop: "https://i.imgur.com/kDJ0kef.png",
        backgroundImage: "https://i.imgur.com/bwICmhF.jpg",
        logo: "https://i.imgur.com/t9EF4JY.png",
        learnMoreLink: "",
    },
]

export default food
