const games = [
	{
		name: "Valorant",
		gif: "https://media1.giphy.com/media/sUOkBnwf8157cVGE57/giphy.gif?cid=ecf05e4703e5a5ex62s18ss4j1acjuz0ewmds422kvnerxnu&rid=giphy.gif&ct=g",
		imagePop: "https://i.imgur.com/5lZwY9B.png",
		backgroundImage: "https://i.imgur.com/DkNDM2i.jpg",
		logo: "https://i.imgur.com/UH4e9t5.png",
		learnMoreLink: "https://playvalorant.com/",
	},
	{
		name: "Fortnite",
		gif: "https://media2.giphy.com/media/EluFWEdnZtvqwZFTQH/giphy.gif?cid=ecf05e47vwlpu23b1ju0m0y4ji6vo2vc6c3obtf12ncehz0h&rid=giphy.gif&ct=g",
		imagePop: "https://i.imgur.com/yMw5Zrc.png",
		backgroundImage: "https://i.imgur.com/LVDzV84.png",
		logo: "https://i.imgur.com/49cBs1z.png",
		learnMoreLink: "https://www.epicgames.com/fortnite/en-US/",
	},
	{
		name: "Dead by Daylight",
		gif: "https://media1.giphy.com/media/JmsU3a2B7IGwxpEqHR/giphy.gif?cid=ecf05e47zlycj5xmpeywvvp2o4m690xwqd552quuow8d60ys&rid=giphy.gif&ct=g",
		imagePop: "https://i.imgur.com/GV3WHsB.png",
		backgroundImage: "https://i.imgur.com/vyj5DId.jpg",
		logo: "https://i.imgur.com/BRgsRFh.png",
		learnMoreLink: "https://deadbydaylight.com/",
	},
	{
		name: "League of Legends",
		gif: "https://media2.giphy.com/media/2sfHBti8mqSO5Bhlqq/giphy.gif?cid=ecf05e476wujgv4s76ash05itqp4jeisws06qq0enbaa9rcr&rid=giphy.gif&ct=g",
		imagePop: "https://i.imgur.com/bldxoqU.png",
		backgroundImage: "https://i.imgur.com/3LzGOd5.jpg",
		logo: "https://i.imgur.com/pA1Gepg.png",
		learnMoreLink: "https://www.leagueoflegends.com/en-au/",
	},
	{
		name: "Stardew Valley",
		gif: "https://media2.giphy.com/media/ecNN1uKqgRaKs/giphy.gif?cid=ecf05e473sedlxv9erym4axxpenvwoq3sn98xalj56hxgkad&rid=giphy.gif&ct=g",
		imagePop: "https://i.imgur.com/r1MOVFB.png",
		backgroundImage: "https://i.imgur.com/aguU78o.jpg",
		logo: "https://i.imgur.com/oxR8oRs.png",
		learnMoreLink: "https://www.stardewvalley.net/",
	},
	{
		name: "Raft",
		gif: "https://media.tenor.com/DeRaWfAyU5IAAAAC/shark-raft.gif",
		imagePop: "https://i.imgur.com/moB4SnZ.png",
		backgroundImage: "https://i.imgur.com/C1uNzJI.png",
		logo: "https://i.imgur.com/2yuwOfu.png",
		learnMoreLink: "https://raft-game.com/",
	},
	{
		name: "Minecraft",
		gif: "https://media3.giphy.com/media/HCLbhUDRzDxbUClyxl/giphy.gif?cid=ecf05e4738yrg17tul9c4rhj6vy3dqj3jc3rzjywu4phbo8x&rid=giphy.gif&ct=g",
		imagePop: "https://i.imgur.com/w9ulgCe.png",
		backgroundImage: "https://i.imgur.com/UiuvuUH.jpg",
		logo: "https://i.imgur.com/2YaoeEV.png",
		learnMoreLink: "https://www.minecraft.net/en-us",
	},
	{
		name: "Among Us",
		gif: "https://media4.giphy.com/media/ZLAUOpqEMsqVYcuOWP/giphy.gif?cid=ecf05e47a8lygz2xg66t61c6z3nt1eyihhxdhil78772jloh&rid=giphy.gif&ct=g",
		imagePop: "https://i.imgur.com/cEya7AE.png",
		backgroundImage: "https://i.imgur.com/KTjEgO1.jpg",
		logo: "https://i.imgur.com/Jth54Ix.png",
		learnMoreLink: "https://www.innersloth.com/games/among-us/",
	},
	{
		name: "Astroneer",
		gif: "https://media.tenor.com/pA5ZvEn_SiIAAAAC/astroneer-astronaut.gif",
		imagePop: "https://i.imgur.com/6Ioheyv.png",
		backgroundImage: "https://i.imgur.com/QIzqzJB.png",
		logo: "https://i.imgur.com/HuNzb8p.png",
		learnMoreLink: "https://astroneer.space/",
	},
	{
		name: "Rust",
		gif: "https://media3.giphy.com/media/ENcUVunGzRnrCBmua0/giphy.gif?cid=ecf05e471gi9dh08r4z2o4ezay4aj5uzikmccnw13djegg2t&rid=giphy.gif&ct=g",
		imagePop: "https://i.imgur.com/Tl8Nnn9.png",
		backgroundImage: "https://i.imgur.com/dJ9qwSg.jpg",
		logo: "https://i.imgur.com/PY2S0Nj.png",
		learnMoreLink: "https://rust.facepunch.com/",
	},
	{
		name: "Roblox",
		gif: "https://media.tenor.com/-Eo0c-54770AAAAC/roblox-noob-roblox.gif",
		imagePop: "https://i.imgur.com/LPCZlYv.png",
		backgroundImage: "https://i.imgur.com/gL8uduN.jpg",
		logo: "https://i.imgur.com/L5nYqq1.png",
		learnMoreLink: "https://www.roblox.com/",
	},
	{
		name: "Overwatch 2",
		gif: "https://media3.giphy.com/media/STZnLEJxMIJ16qetcj/giphy.gif?cid=ecf05e47e38m641isfrlvxvdg4qoqy4o9pwb9ze2c5uviqrm&rid=giphy.gif&ct=g",
		imagePop: "https://i.imgur.com/aZIQzTl.png",
		backgroundImage: "https://i.imgur.com/HeChcUH.jpg",
		logo: "https://i.imgur.com/Qhnw7bt.png",
		learnMoreLink: "https://overwatch.blizzard.com/en-us/",
	},
	{
		name: "Propnight",
		gif: "https://i.imgur.com/FrsGmYN.gif",
		imagePop: "https://i.imgur.com/dNKR7to.png",
		backgroundImage: "https://i.imgur.com/45vhQWZ.jpg",
		logo: "https://i.imgur.com/1mtzbMq.png",
		learnMoreLink: "https://www.propnight.com/",
	},
	{
		name: "Mario Kart",
		gif: "https://i.imgur.com/mlPK45f.gif",
		imagePop: "https://i.imgur.com/89YC2I9.png",
		backgroundImage: "https://i.imgur.com/rcsW37b.jpg",
		logo: "https://i.imgur.com/5AM7lLR.png",
		learnMoreLink:
			"https://www.nintendo.com.au/games/nintendo-switch/mario-kart-8-deluxe",
	},
	{
		name: "Counter-Strike: Global Offensive",
		gif: "https://i.imgur.com/QkPGZzg.gif",
		imagePop: "https://i.imgur.com/twsyWww.png",
		backgroundImage: "https://i.imgur.com/1hXTTUh.jpg",
		logo: "https://i.imgur.com/tIqZLRb.png",
		learnMoreLink: "https://blog.counter-strike.net/",
	},
	{
		name: "PlateUp!",
		gif: "https://i.imgur.com/G7PedTT.gif",
		imagePop: "https://i.imgur.com/3Yon8bB.png",
		backgroundImage: "https://i.imgur.com/ZaeCsg7.jpg",
		logo: "https://i.imgur.com/v2JHOLP.png",
		learnMoreLink: "https://www.plateupgame.com/",
	},
	{
		name: "RuneScape",
		gif: "https://media2.giphy.com/media/XxqDdWZYXGHtfx1uO8/giphy.gif?cid=ecf05e47b2bs1zo4yr55il4ats1ke9alcqvf2ckxr796xdqv&rid=giphy.gif&ct=g",
		imagePop: "https://i.imgur.com/Op6Ltva.png",
		backgroundImage: "https://i.imgur.com/M6rT0eU.jpg",
		logo: "https://i.imgur.com/MMJbGjJ.png",
		learnMoreLink: "https://play.runescape.com/",
	},
	{
		name: "World of Warcraft",
		gif: "https://media1.giphy.com/media/21PeokB8uIQvjIhVO5/giphy.gif?cid=ecf05e47yzhuz7qnb38o6616x1hqwz9vrhxjx38kv2topbpd&rid=giphy.gif&ct=g",
		imagePop: "https://i.imgur.com/tlc8vl9.png",
		backgroundImage: "https://i.imgur.com/BMlYj93.jpg",
		logo: "https://i.imgur.com/vAAxzya.png",
		learnMoreLink: "https://worldofwarcraft.com/en-us/",
	},
];

export default games;
